
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR_TEXTO_BLOQUE = 46;
  public static final int LETRA_SIZE_MIENTRAS = 45;
  public static final int PARENTESIS_CIERRA = 28;
  public static final int ENTERO = 29;
  public static final int SI = 4;
  public static final int MOSTRAR = 10;
  public static final int FIGURA_BLOQUE = 48;
  public static final int DIFERENTE = 19;
  public static final int RESTA = 14;
  public static final int PC = 54;
  public static final int PORCENTAJE = 60;
  public static final int LETRA_MIENTRAS = 44;
  public static final int ENTONCES = 5;
  public static final int PA = 53;
  public static final int FIN = 3;
  public static final int NOT = 26;
  public static final int MENORIGUAL = 23;
  public static final int AND = 24;
  public static final int IGUAL = 17;
  public static final int FINMIENTRAS = 8;
  public static final int OR = 25;
  public static final int MIENTRAS = 6;
  public static final int LETRA_SIZE_BLOQUE = 50;
  public static final int SUMA = 13;
  public static final int MAYORIGUAL = 22;
  public static final int EOF = 0;
  public static final int DECIMAL = 30;
  public static final int error = 1;
  public static final int COMA = 52;
  public static final int COLOR_BLOQUE = 47;
  public static final int SEPARADORSECCION = 58;
  public static final int PIPE = 51;
  public static final int CADENA = 31;
  public static final int COMENTARIO = 32;
  public static final int COLOR_MIENTRAS = 42;
  public static final int MENOR = 21;
  public static final int COLOR_TEXTO_MIENTRAS = 41;
  public static final int LETRA_BLOQUE = 49;
  public static final int ERROR = 33;
  public static final int MAYOR = 20;
  public static final int VARIABLE = 34;
  public static final int IGUALIGUAL = 18;
  public static final int FIGURA_MIENTRAS = 43;
  public static final int IGUALCONF = 59;
  public static final int DEFAULT = 35;
  public static final int LEER = 11;
  public static final int HACER = 9;
  public static final int MULTI = 15;
  public static final int LETRA_SI = 39;
  public static final int COLOR_SI = 37;
  public static final int HEXCOLOR = 55;
  public static final int INICIO = 2;
  public static final int FINSI = 7;
  public static final int DIVISION = 16;
  public static final int COLOR_TEXTO_SI = 36;
  public static final int FIGURA_SI = 38;
  public static final int VAR = 12;
  public static final int PARENTESIS_ABRE = 27;
  public static final int FIGURA = 56;
  public static final int FUENTE = 57;
  public static final int LETRA_SIZE_SI = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "FINSI",
  "FINMIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "VAR",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVISION",
  "IGUAL",
  "IGUALIGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "NOT",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "COMENTARIO",
  "ERROR",
  "VARIABLE",
  "DEFAULT",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "PIPE",
  "COMA",
  "PA",
  "PC",
  "HEXCOLOR",
  "FIGURA",
  "FUENTE",
  "SEPARADORSECCION",
  "IGUALCONF",
  "PORCENTAJE"
  };
}

