
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 24;
  public static final int MENOR = 21;
  public static final int IGUALIGUAL = 18;
  public static final int CADENA = 30;
  public static final int OR = 25;
  public static final int MENORIGUAL = 23;
  public static final int IGUAL = 17;
  public static final int DECIMAL = 29;
  public static final int DIVISION = 16;
  public static final int SUMA = 13;
  public static final int PARENTESIS_ABRE = 26;
  public static final int LEER = 11;
  public static final int ENTONCES = 5;
  public static final int MULTI = 15;
  public static final int ERROR = 32;
  public static final int PARENTESIS_CIERRA = 27;
  public static final int VARIABLE = 33;
  public static final int MAYOR = 20;
  public static final int EOF = 0;
  public static final int MOSTRAR = 10;
  public static final int FINMIENTRAS = 8;
  public static final int DIFERENTE = 19;
  public static final int MAYORIGUAL = 22;
  public static final int SI = 4;
  public static final int error = 1;
  public static final int ENTERO = 28;
  public static final int COMENTARIO = 31;
  public static final int MIENTRAS = 6;
  public static final int FINSI = 7;
  public static final int HACER = 9;
  public static final int FIN = 3;
  public static final int VAR = 12;
  public static final int RESTA = 14;
  public static final int INICIO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "FINSI",
  "FINMIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "VAR",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVISION",
  "IGUAL",
  "IGUALIGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "COMENTARIO",
  "ERROR",
  "VARIABLE"
  };
}

